### ISSUE TITLE
Better Pipe support?

### ISSUE THREAD

**Issue by rockerBOO** [hahuang65/beaker#1]
Right now I am wanting to do this, but the key being in the front is not making it possible. Not sure what the most used cases are here, but something to consider.

```elixir
    Counter.get(key)
      |> TimeSeries.sample(key)
      |> Counter.set(0)
```

Thanks for this great library! Works beautifully!

**Comment by hahuang65** [comment]
@rockerBOO first of all, I can't believe you're using this. I haven't even release 1.0. But I'm glad you are! I'd love feedback.

So I had been considering this exact issue a few days ago and I wasn't so sure what the answer would be here.

Better pipe support would be amazing, but at the same time, it feels wrong to switch the function signature from
`Counter.set(key, value)`
to
`Counter.set(value, key)`

Here in you're example,  you have 2 conflicting uses of pipes. When you pipe to `TimeSeries.sample` you are sending a value, but when you pipe to `Counter.set`, you are piping a key... We won't be able to have both... What do you think would be more used?

My guess is that piping a value in would be more common, since it'd look like:

```elixir
some_complex_calculation
|> TimeSeries.sample("foo")
```

**Comment by rockerBOO** [comment]
I have played with the 2 signatures, and gets tricky if the use case changes at all. I think pipes are too cool though to not write code to take advantage of them. I think (value, key) is not too confusing and I think of it as "Counter sample value into key". `TimeSeries.sample` seems to be the only one so far that is throwing me I suppose. 

Right now, my use case is using [quantum](https://github.com/c-rack/quantum-elixir) (cron job like), to take the counts, and save them into a TimeSeries flow every min.

```elixir
count = Counter.get(key)
TimeSeries.sample(key, count)
Counter.set(key, 0)
```

**Comment by hahuang65** [comment]
@rockerBOO I'm actually not going to support this. I talked to a few Elixir guys, namely Jose, and he said to please not do this type of thing just to support pipes :).
